// Code generated by protoc-gen-go.
// source: decoderbufs/decoderbufs.proto
// DO NOT EDIT!

/*
Package decoderbufs is a generated protocol buffer package.

It is generated from these files:
	decoderbufs/decoderbufs.proto

It has these top-level messages:
	Point
	DatumMessage
	RowMessage
*/
package decoderbufs

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Op int32

const (
	Op_INSERT Op = 0
	Op_UPDATE Op = 1
	Op_DELETE Op = 2
)

var Op_name = map[int32]string{
	0: "INSERT",
	1: "UPDATE",
	2: "DELETE",
}
var Op_value = map[string]int32{
	"INSERT": 0,
	"UPDATE": 1,
	"DELETE": 2,
}

func (x Op) Enum() *Op {
	p := new(Op)
	*p = x
	return p
}
func (x Op) String() string {
	return proto.EnumName(Op_name, int32(x))
}
func (x *Op) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(Op_value, data, "Op")
	if err != nil {
		return err
	}
	*x = Op(value)
	return nil
}
func (Op) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

type Point struct {
	X                *float64 `protobuf:"fixed64,1,req,name=x" json:"x,omitempty"`
	Y                *float64 `protobuf:"fixed64,2,req,name=y" json:"y,omitempty"`
	XXX_unrecognized []byte   `json:"-"`
}

func (m *Point) Reset()                    { *m = Point{} }
func (m *Point) String() string            { return proto.CompactTextString(m) }
func (*Point) ProtoMessage()               {}
func (*Point) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *Point) GetX() float64 {
	if m != nil && m.X != nil {
		return *m.X
	}
	return 0
}

func (m *Point) GetY() float64 {
	if m != nil && m.Y != nil {
		return *m.Y
	}
	return 0
}

type DatumMessage struct {
	ColumnName       *string  `protobuf:"bytes,1,opt,name=column_name" json:"column_name,omitempty"`
	ColumnType       *int64   `protobuf:"varint,2,opt,name=column_type" json:"column_type,omitempty"`
	DatumInt32       *int32   `protobuf:"varint,3,opt,name=datum_int32" json:"datum_int32,omitempty"`
	DatumInt64       *int64   `protobuf:"varint,4,opt,name=datum_int64" json:"datum_int64,omitempty"`
	DatumFloat       *float32 `protobuf:"fixed32,5,opt,name=datum_float" json:"datum_float,omitempty"`
	DatumDouble      *float64 `protobuf:"fixed64,6,opt,name=datum_double" json:"datum_double,omitempty"`
	DatumBool        *bool    `protobuf:"varint,7,opt,name=datum_bool" json:"datum_bool,omitempty"`
	DatumString      *string  `protobuf:"bytes,8,opt,name=datum_string" json:"datum_string,omitempty"`
	DatumBytes       []byte   `protobuf:"bytes,9,opt,name=datum_bytes" json:"datum_bytes,omitempty"`
	DatumPoint       *Point   `protobuf:"bytes,10,opt,name=datum_point" json:"datum_point,omitempty"`
	UnchangedNoValue *bool    `protobuf:"varint,11,opt,name=unchanged_no_value" json:"unchanged_no_value,omitempty"`
	XXX_unrecognized []byte   `json:"-"`
}

func (m *DatumMessage) Reset()                    { *m = DatumMessage{} }
func (m *DatumMessage) String() string            { return proto.CompactTextString(m) }
func (*DatumMessage) ProtoMessage()               {}
func (*DatumMessage) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *DatumMessage) GetColumnName() string {
	if m != nil && m.ColumnName != nil {
		return *m.ColumnName
	}
	return ""
}

func (m *DatumMessage) GetColumnType() int64 {
	if m != nil && m.ColumnType != nil {
		return *m.ColumnType
	}
	return 0
}

func (m *DatumMessage) GetDatumInt32() int32 {
	if m != nil && m.DatumInt32 != nil {
		return *m.DatumInt32
	}
	return 0
}

func (m *DatumMessage) GetDatumInt64() int64 {
	if m != nil && m.DatumInt64 != nil {
		return *m.DatumInt64
	}
	return 0
}

func (m *DatumMessage) GetDatumFloat() float32 {
	if m != nil && m.DatumFloat != nil {
		return *m.DatumFloat
	}
	return 0
}

func (m *DatumMessage) GetDatumDouble() float64 {
	if m != nil && m.DatumDouble != nil {
		return *m.DatumDouble
	}
	return 0
}

func (m *DatumMessage) GetDatumBool() bool {
	if m != nil && m.DatumBool != nil {
		return *m.DatumBool
	}
	return false
}

func (m *DatumMessage) GetDatumString() string {
	if m != nil && m.DatumString != nil {
		return *m.DatumString
	}
	return ""
}

func (m *DatumMessage) GetDatumBytes() []byte {
	if m != nil {
		return m.DatumBytes
	}
	return nil
}

func (m *DatumMessage) GetDatumPoint() *Point {
	if m != nil {
		return m.DatumPoint
	}
	return nil
}

func (m *DatumMessage) GetUnchangedNoValue() bool {
	if m != nil && m.UnchangedNoValue != nil {
		return *m.UnchangedNoValue
	}
	return false
}

type RowMessage struct {
	CommitTime       *uint64         `protobuf:"varint,1,opt,name=commit_time" json:"commit_time,omitempty"`
	LogPosition      *uint64         `protobuf:"varint,2,opt,name=log_position" json:"log_position,omitempty"`
	Table            *string         `protobuf:"bytes,3,opt,name=table" json:"table,omitempty"`
	Op               *Op             `protobuf:"varint,4,opt,name=op,enum=decoderbufs.Op" json:"op,omitempty"`
	NewTuple         []*DatumMessage `protobuf:"bytes,5,rep,name=new_tuple" json:"new_tuple,omitempty"`
	OldTuple         []*DatumMessage `protobuf:"bytes,6,rep,name=old_tuple" json:"old_tuple,omitempty"`
	XXX_unrecognized []byte          `json:"-"`
}

func (m *RowMessage) Reset()                    { *m = RowMessage{} }
func (m *RowMessage) String() string            { return proto.CompactTextString(m) }
func (*RowMessage) ProtoMessage()               {}
func (*RowMessage) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *RowMessage) GetCommitTime() uint64 {
	if m != nil && m.CommitTime != nil {
		return *m.CommitTime
	}
	return 0
}

func (m *RowMessage) GetLogPosition() uint64 {
	if m != nil && m.LogPosition != nil {
		return *m.LogPosition
	}
	return 0
}

func (m *RowMessage) GetTable() string {
	if m != nil && m.Table != nil {
		return *m.Table
	}
	return ""
}

func (m *RowMessage) GetOp() Op {
	if m != nil && m.Op != nil {
		return *m.Op
	}
	return Op_INSERT
}

func (m *RowMessage) GetNewTuple() []*DatumMessage {
	if m != nil {
		return m.NewTuple
	}
	return nil
}

func (m *RowMessage) GetOldTuple() []*DatumMessage {
	if m != nil {
		return m.OldTuple
	}
	return nil
}

func init() {
	proto.RegisterType((*Point)(nil), "decoderbufs.Point")
	proto.RegisterType((*DatumMessage)(nil), "decoderbufs.DatumMessage")
	proto.RegisterType((*RowMessage)(nil), "decoderbufs.RowMessage")
	proto.RegisterEnum("decoderbufs.Op", Op_name, Op_value)
}

func init() { proto.RegisterFile("decoderbufs/decoderbufs.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 378 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0x84, 0x92, 0xcd, 0x4a, 0xc3, 0x40,
	0x14, 0x85, 0x9d, 0xa4, 0xa9, 0xcd, 0x4d, 0xd5, 0x3a, 0xba, 0x18, 0x95, 0x42, 0xe9, 0xc6, 0x20,
	0x52, 0xa1, 0x8a, 0x7b, 0x4b, 0x03, 0x0a, 0xfe, 0x84, 0x5a, 0xd7, 0x21, 0x6d, 0xa6, 0x31, 0x30,
	0x99, 0x09, 0xcd, 0xc4, 0xda, 0xc7, 0xf0, 0x89, 0x7c, 0x35, 0x67, 0xfa, 0x83, 0x09, 0x2e, 0xdc,
	0x1d, 0x3e, 0xce, 0xcd, 0x3d, 0xf7, 0x64, 0xa0, 0x1d, 0xd1, 0xa9, 0x88, 0xe8, 0x7c, 0x52, 0xcc,
	0xf2, 0xab, 0x92, 0xee, 0x65, 0x73, 0x21, 0x05, 0x76, 0x4a, 0xa8, 0xdb, 0x06, 0xcb, 0x17, 0x09,
	0x97, 0xd8, 0x06, 0xf4, 0x49, 0x50, 0xc7, 0x70, 0x91, 0x96, 0x4b, 0x62, 0x68, 0xd9, 0xfd, 0x32,
	0xa0, 0x39, 0x0c, 0x65, 0x91, 0x3e, 0xd1, 0x3c, 0x0f, 0x63, 0x8a, 0x8f, 0xc0, 0x99, 0x0a, 0x56,
	0xa4, 0x3c, 0xe0, 0x61, 0x4a, 0xd5, 0x00, 0x72, 0xed, 0x12, 0x94, 0xcb, 0x8c, 0xaa, 0x51, 0xe4,
	0x9a, 0x1a, 0x46, 0x7a, 0x32, 0x50, 0x5f, 0xbf, 0xee, 0x13, 0x53, 0x41, 0xab, 0x02, 0x6f, 0x6f,
	0x48, 0xad, 0xea, 0x9c, 0x31, 0x11, 0x4a, 0x62, 0x29, 0x68, 0xe0, 0x63, 0x68, 0xae, 0x61, 0x24,
	0x8a, 0x09, 0xa3, 0xa4, 0xae, 0x28, 0xc2, 0x18, 0x60, 0x4d, 0x27, 0x42, 0x30, 0xb2, 0xab, 0x58,
	0xe3, 0xd7, 0x99, 0xcb, 0x79, 0xc2, 0x63, 0xd2, 0xd8, 0x66, 0xda, 0x38, 0x97, 0x92, 0xe6, 0xc4,
	0x56, 0xb0, 0x89, 0xcf, 0xb7, 0x30, 0xd3, 0x37, 0x13, 0x50, 0xd0, 0xe9, 0xe3, 0x5e, 0xb9, 0xa3,
	0x75, 0x1b, 0xa7, 0x80, 0x0b, 0x3e, 0x7d, 0x0f, 0x79, 0x4c, 0xa3, 0x80, 0x8b, 0xe0, 0x23, 0x64,
	0x05, 0x25, 0x8e, 0xde, 0xd7, 0xfd, 0x46, 0x00, 0x23, 0xb1, 0xa8, 0x34, 0x92, 0xa6, 0x89, 0x0c,
	0x64, 0xb2, 0x69, 0xa4, 0xa6, 0x33, 0x31, 0x11, 0xab, 0x35, 0x79, 0x22, 0x13, 0xc1, 0x57, 0x95,
	0xd4, 0xf0, 0x1e, 0x58, 0x32, 0xd4, 0xc7, 0x98, 0xab, 0x88, 0x67, 0x60, 0x88, 0x6c, 0xd5, 0xc1,
	0x7e, 0xff, 0xa0, 0x12, 0xe2, 0x25, 0xc3, 0x97, 0x60, 0x73, 0xba, 0x08, 0x64, 0x91, 0x29, 0xbf,
	0xd5, 0x31, 0x55, 0xd0, 0x93, 0x8a, 0xa7, 0xf2, 0x5b, 0x94, 0x5b, 0xb0, 0x68, 0xe3, 0xae, 0xff,
	0xe3, 0xbe, 0x70, 0xc1, 0x50, 0x1b, 0x00, 0xea, 0x0f, 0xcf, 0xaf, 0xde, 0x68, 0xdc, 0xda, 0xd1,
	0xfa, 0xcd, 0x1f, 0xde, 0x8d, 0xbd, 0x16, 0xd2, 0x7a, 0xe8, 0x3d, 0x7a, 0x4a, 0x1b, 0x83, 0x0e,
	0x1c, 0xfe, 0x79, 0x40, 0x03, 0xdb, 0x8f, 0x59, 0xe4, 0x6b, 0x79, 0x8f, 0x7e, 0x02, 0x00, 0x00,
	0xff, 0xff, 0x78, 0x0b, 0xb7, 0xc6, 0x6d, 0x02, 0x00, 0x00,
}
